language: node_js
node_js:
  - "stable"
cache:
  directories:
    -node_modules
    - ~/.npm
    - ~/.cache
  install:
  - npm ci
env:
  global:
    - CC_TEST_REPORTER_ID=af8d9d8f814dfe4415fc628668f8f1f96efb8d1c1b3ce87324b5ff63d144e252
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - webpack-dev-server & $(npm bin)/cypress run
  - npm test
    
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT