const constants = {
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',
  CREATE_ACCOUNT_ERROR: 'CREATE_ACCOUNT_ERROR',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  GET_RIDES: 'GET_RIDES',
  GET_RIDES_SUCCESS: 'GET_RIDES_SUCCESS',
  GET_RIDES_ERROR: 'GET_RIDES_ERROR',
  GET_SINGLE_RIDE: 'GET_SINGLE_RIDE',
  GET_SINGLE_RIDE_SUCCESS: 'GET_SINGLE_RIDE_SUCCESS',
  GET_SINGLE_RIDE_ERROR: 'GET_SINGLE_RIDE_ERROR',
  JOIN_RIDE: 'JOIN_RIDE',
  JOIN_RIDE_SUCCESS: 'JOIN_RIDE_SUCCESS',
  JOIN_RIDE_ERROR: 'JOIN_RIDE_ERROR',
  CREATE_RIDE: 'CREATE_RIDE',
  CREATE_RIDE_SUCCESS: 'CREATE_RIDE_SUCCESS',
  CREATE_RIDE_ERROR: 'CREATE_RIDE_ERROR',
};

export default constants;
